package cool.happyword.wordmagic.ui.navigation

internal enum class AppRoute {
    Home,
    Battle,
    Result,
    Config,
    ParentPin,
    ParentAdmin,
    LessonDraftReview,
    PackManager,
    Wishlist,
    RedemptionHistory,
    MonsterCodex,
    Spellbook,
    TodayPlan,
    LearningReport,
    CheckInCalendar,
    ScanBinding,
    BoundDeviceInfo,
    DevMenu,
    DomainSwitch,
    PcmAudioLab,
    MessageBubbleLab,
}
