#pragma once

// Mirrors the compile definitions the Cocos-generated app target passes via
// CMake (see cocos/build/ios/proj response files). Engine headers branch
// on these, so this prelude MUST be included before any engine header.

#define CC_PLATFORM_UNKNOWN 0
#define CC_PLATFORM_IOS 1
#define CC_PLATFORM_WINDOWS 2
#define CC_PLATFORM_ANDROID 3
#define CC_PLATFORM_MACOS 4
#define CC_PLATFORM_OHOS 5
#define CC_PLATFORM_LINUX 6
#define CC_PLATFORM_QNX 7
#define CC_PLATFORM_NX 8
#define CC_PLATFORM_EMSCRIPTEN 9
#define CC_PLATFORM_OPENHARMONY 10
#define CC_PLATFORM_MAC_IOS 1
#define CC_PLATFORM_MAC_OSX 4
#define CC_PLATFORM 1

#define CC_EDITOR 0
#define CC_NETMODE_CLIENT 0
#define CC_NETMODE_LISTEN_SERVER 1
#define CC_NETMODE_HOST_SERVER 2
#define CC_NETMODE 0

#define CC_USE_METAL 1
#define CC_USE_AUDIO 1
#define CC_USE_VIDEO 1
#define CC_USE_WEBVIEW 1
#define CC_USE_EDITBOX 1
#define CC_USE_GAMEPAD 1
#define CC_USE_MIDDLEWARE 1
#define CC_USE_SPINE 1
#define CC_USE_SPINE_3_8 1
#define CC_USE_SPINE_4_2 0
#define CC_USE_DRAGONBONES 1
#define CC_USE_WEBP 1
#define CC_USE_SOCKET 0
#define CC_USE_WEBSOCKET_SERVER 0
#define CC_USE_DEBUG_RENDERER 0
#define CC_USE_GEOMETRY_RENDERER 0
#define CC_USE_OCCLUSION_QUERY 0
#define CC_USE_PHYSICS_PHYSX 0
#define CC_USE_BOX2D_JSB 0
#define CC_USE_JOB_SYSTEM_TASKFLOW 0
#define CC_USE_JOB_SYSTEM_TBB 0
#define CC_USE_XR 0
#define CC_USE_XR_REMOTE_PREVIEW 0
#define CC_USE_AR_MODULE 0
#define CC_USE_AR_AUTO 0
#define CC_USE_AR_CORE 0
#define CC_USE_AR_ENGINE 0
#define CC_USE_ADPF 0
#define CC_USE_GOOGLE_BILLING 0
#define CC_USE_GOOGLE_PLAY_GAMES 0

#define SCRIPT_ENGINE_TYPE 2
#define USE_V8_DEBUGGER 0
#define ENABLE_FLOAT_OUTPUT 0
#define OBJC_OLD_DISPATCH_PROTOTYPES 1
#define TBB_USE_EXCEPTIONS 0

#define BOOST_ALL_NO_LIB 1
#define BOOST_CONTAINER_NO_LIB 1
#define BOOST_CONTAINER_STATIC_LINK 1
#define BOOST_NO_CXX98_FUNCTION_BASE 1
#define BOOST_UUID_FORCE_AUTO_LINK 1

#define V8_ATOMIC_OBJECT_FIELD_WRITES 1
#define V8_ATOMIC_MARKING_STATE 1
#define V8_ENABLE_LAZY_SOURCE_POSITIONS 1
#define V8_SHARED_RO_HEAP 1
#define V8_WIN64_UNWINDING_INFO 1
#define V8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH 1
#define V8_SNAPSHOT_COMPRESSION 1
#define V8_ENABLE_SYSTEM_INSTRUMENTATION 1
#define V8_ENABLE_WEBASSEMBLY 1
#define V8_DEPRECATION_WARNINGS 1
#define V8_IMMINENT_DEPRECATION_WARNINGS 1
#define CPPGC_CAGED_HEAP 1
#define V8_TARGET_ARCH_ARM64 1
#define V8_HAVE_TARGET_OS 1
#define V8_TARGET_OS_IOS 1
#define V8_TYPED_ARRAY_MAX_SIZE_IN_HEAP 64
#define DISABLE_UNTRUSTED_CODE_MITIGATIONS 1
#define ENABLE_MINOR_MC 1
#define ENABLE_HANDLE_ZAPPING 1
