#!/usr/bin/env bash
# Rasterise the v0.3.10 launcher SVGs into the entry/src/main/resources/base/media/
# layered-image PNGs that HarmonyOS reads at runtime.
#
# Inputs (must already be generated by tools/recraft/generate-icons.sh):
#   generated/recraft/icons/foreground.svg
#   generated/recraft/icons/background.svg
#   generated/recraft/icons/startIcon.svg
#
# Outputs (overwritten):
#   entry/src/main/resources/base/media/foreground.png   1024x1024
#   entry/src/main/resources/base/media/background.png   1024x1024
#   entry/src/main/resources/base/media/startIcon.png    216x216
#
# layered_image.json continues to reference $media:foreground / $media:background;
# module.json5 / app.json5 continue to reference $media:layered_image / $media:startIcon.
# So this script doesn't touch any manifest — only the PNG bytes.
set -euo pipefail
cd "$(dirname "$0")/../.."

SRC="generated/recraft/icons"
DST="entry/src/main/resources/base/media"

if ! command -v rsvg-convert >/dev/null 2>&1; then
  echo "rsvg-convert not found on PATH. Install librsvg, e.g. \`brew install librsvg\`." >&2
  exit 1
fi

for n in foreground background startIcon; do
  if [[ ! -f "$SRC/$n.svg" ]]; then
    echo "Missing source SVG: $SRC/$n.svg (run generate-icons.sh first)" >&2
    exit 1
  fi
done

node tools/recraft/svg-to-png.mjs --in "$SRC/foreground.svg" --out "$DST/foreground.png" --size 1024
node tools/recraft/svg-to-png.mjs --in "$SRC/background.svg" --out "$DST/background.png" --size 1024
node tools/recraft/svg-to-png.mjs --in "$SRC/startIcon.svg"  --out "$DST/startIcon.png"  --size 216

echo ""
echo "=== launcher PNGs ==="
ls -la "$DST/foreground.png" "$DST/background.png" "$DST/startIcon.png"
