#!/bin/bash
# Headless Cocos build for the Android embed.
# Produces cocos/build/android/ (gradle template project + data), then
# vendors the pieces our app needs into android/app/ (engine Java layer +
# data bundle as assets).  Run this once before `cd android && ./gradlew
# :app:assembleDebug` — the assets/cocos data bundle is gitignored and only
# exists after this script ran.
#
# Usage: tools/cocos/build-android.sh [--vendor-only]
#   --vendor-only  skip the Cocos Creator CLI build and only re-run the
#                  vendor/rsync step (useful when iterating on the embed).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CREATOR="/Applications/Cocos/Creator/3.8.8/CocosCreator.app/Contents/MacOS/CocosCreator"

VENDOR_ONLY=0
if [ "${1:-}" = "--vendor-only" ]; then
    VENDOR_ONLY=1
fi

# ---------------------------------------------------------------------------
# Vendor step (Task 0.2): copy the engine Java layer + data bundle into the
# real app at android/app/.
#
# Vendored pieces:
#   * engine com/cocos/lib/*.java  -> android/app/src/main/java/com/cocos/lib/
#     (committed; 25 Java source files that make up the Cocos Android platform
#     layer including CocosActivity, JsbBridgeWrapper, CocosHelper etc.)
#   * cocos/build/android/android/data/ -> android/app/src/main/assets/
#     (gitignored; the template puts "${RES_PATH}/data" as the assets srcDir,
#     so the data dir content becomes the APK assets root; our app replicates
#     the same layout so CocosHelper/FileUtils finds main.js at assets://main.js
#     without any path overrides)
#
# Two scripted fix-ups are applied to vendored files (recorded here on purpose;
# the engine originals under Creator's bundle stay pristine):
#
#   Fix-up 1 — CocosEditBoxActivity.java: the engine's libcocos2dx Android
#     library module defines its own com.cocos.lib namespace, so all `R.string.*`
#     calls there are implicitly qualified `com.cocos.lib.R`.  When the files are
#     inlined into our app module (namespace cool.happyword.wordmagic), `R` must
#     resolve to `cool.happyword.wordmagic.R`.  We add an explicit import AND
#     rename the string keys to the cocos-prefixed names defined in
#     android/app/src/main/res/values/cocos_strings.xml to avoid conflicts with
#     any app string of the same name.
#
#   Fix-up 2 — CocosTouchHandler.java: references `BuildConfig.DEBUG` which is
#     in package `com.cocos.lib` in the original library module.  We add an
#     explicit import pointing at the app's BuildConfig (generated by AGP from
#     the app's applicationId `cool.happyword.wordmagic`).
# ---------------------------------------------------------------------------
vendor_into_android() {
    local ENGINE_JAVA="/Applications/Cocos/Creator/3.8.8/CocosCreator.app/Contents/Resources/resources/3d/engine/native/cocos/platform/android/java/src/com/cocos/lib"
    local APP="$ROOT/android/app/src/main"
    local JAVA_DEST="$APP/java/com/cocos/lib"

    echo "==> vendoring engine Java layer into android/app/src/main/java/com/cocos/lib"
    mkdir -p "$JAVA_DEST"
    rsync -a --delete "$ENGINE_JAVA/" "$JAVA_DEST/"

    # Fix-up 1: CocosEditBoxActivity — add R import; rename string keys.
    # `sed -i ''` is intentionally BSD/macOS sed (this script is macOS-bound).
    local EDITBOX="$JAVA_DEST/CocosEditBoxActivity.java"
    sed -i '' \
        's/^import android\.app\.Activity;/import android.app.Activity;\nimport cool.happyword.wordmagic.R;/' \
        "$EDITBOX"
    sed -i '' \
        's/R\.string\.done/R.string.cocos_done/g;
         s/R\.string\.next/R.string.cocos_next/g;
         s/R\.string\.search/R.string.cocos_search/g;
         s/R\.string\.go/R.string.cocos_go/g;
         s/R\.string\.send/R.string.cocos_send/g;
         s/R\.string\.tip_disable_safe_input_type/R.string.cocos_tip_disable_safe_input_type/g' \
        "$EDITBOX"
    grep -q 'import cool.happyword.wordmagic.R;' "$EDITBOX" || {
        echo "fix-up 1 (R import) did not apply (Creator template changed?)" >&2; exit 1
    }
    grep -q 'R\.string\.cocos_done' "$EDITBOX" || {
        echo "fix-up 1 (string rename) did not apply (Creator template changed?)" >&2; exit 1
    }

    # Fix-up 2: CocosTouchHandler — replace BuildConfig.DEBUG with the
    # android.os.Build constant equivalent so we don't depend on the AGP-
    # generated BuildConfig class (which requires buildFeatures.buildConfig=true
    # and whose package differs between the library and app modules).
    # 0 != 0 is always false (never DEBUG) — a safe conservative substitution
    # for the motion-event verbose log guard.
    # `sed -i ''` is intentionally BSD/macOS sed (this script is macOS-bound).
    local TOUCH="$JAVA_DEST/CocosTouchHandler.java"
    sed -i '' \
        's/BuildConfig\.DEBUG/(0 != 0) \/* WMG fix-up 2: BuildConfig.DEBUG stub *\//' \
        "$TOUCH"
    grep -q 'WMG fix-up 2' "$TOUCH" || {
        echo "fix-up 2 (BuildConfig.DEBUG stub) did not apply (Creator template changed?)" >&2; exit 1
    }

    echo "==> vendoring data bundle into android/app/src/main/assets (gitignored, ~14MB)"
    mkdir -p "$APP/assets"
    rsync -a --delete "$ROOT/cocos/build/android/android/data/" "$APP/assets/"

    echo "==> vendor step done"
}

if [ "$VENDOR_ONLY" -eq 1 ]; then
    vendor_into_android
    exit 0
fi

echo "==> quitting Cocos Creator (CLI build requires exclusive project lock)"
osascript -e 'tell application "CocosCreator" to quit' >/dev/null 2>&1 || true
for _ in $(seq 1 20); do
  pgrep -x CocosCreator >/dev/null || break
  sleep 1
done

echo "==> building platform=android"
"$CREATOR" --project "$ROOT/cocos" --build "platform=android" || true
[ -d "$ROOT/cocos/build/android" ] || {
  echo "build output missing; tail of log:" >&2
  tail -40 "$ROOT/cocos/temp/logs/project.log" >&2 || true
  exit 1
}
find "$ROOT/cocos/build/android" -name main.js -path "*data*" | grep -q . || {
  echo "data bundle missing; tail of log:" >&2
  tail -40 "$ROOT/cocos/temp/logs/project.log" >&2
  exit 1
}

vendor_into_android

echo "==> done; output at cocos/build/android/"
