#!/bin/bash
set -euo pipefail
export LC_ALL=C
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/harmonyos/entry/src/test/CocosBridgeFixtures.ets"
compgen -G "$ROOT/shared/fixtures/cocos-battle-bridge/*.json" >/dev/null || {
  echo "no fixtures found in $ROOT/shared/fixtures/cocos-battle-bridge/" >&2
  exit 1
}
{
  echo "// GENERATED by tools/cocos/gen-harmony-fixtures.sh — do not edit."
  echo "export const FIXTURES: Map<string, string> = new Map<string, string>(["
  for f in "$ROOT"/shared/fixtures/cocos-battle-bridge/*.json; do
    name="$(basename "$f" .json)"
    json="$(python3 -c 'import json,sys;print(json.dumps(json.dumps(json.load(open(sys.argv[1])))))' "$f")"
    echo "  ['$name', $json],"
  done
  echo "]);"
} > "$OUT"
echo "wrote $OUT"
