from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SERVER_ROOT = REPO_ROOT / "server"
if str(SERVER_ROOT) not in sys.path:
    sys.path.insert(0, str(SERVER_ROOT))

from app.main import app  # noqa: E402


OPENAPI_PATH = REPO_ROOT / "shared" / "contracts" / "openapi" / "happyword-api.openapi.json"
PATHS_PATH = REPO_ROOT / "shared" / "contracts" / "openapi" / "happyword-api.paths.txt"
SHA_PATH = REPO_ROOT / "shared" / "contracts" / "openapi" / "happyword-api.sha256"


def main() -> None:
    generated = app.openapi()
    generated["info"]["x-contract-source"] = "server/app/main.py"
    generated["info"]["x-contract-note"] = (
        "Generated by tools/contracts/export_openapi.py. Do not edit by hand."
    )
    payload = json.dumps(generated, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    recorded = OPENAPI_PATH.read_text(encoding="utf-8")
    if payload != recorded:
        raise SystemExit(
            "OpenAPI contract is stale. Run: cd server && uv run python ../tools/contracts/export_openapi.py"
        )
    expected_paths = "\n".join(sorted(generated["paths"].keys())) + "\n"
    if PATHS_PATH.read_text(encoding="utf-8") != expected_paths:
        raise SystemExit("OpenAPI paths index is stale.")
    expected_sha = hashlib.sha256(payload.encode("utf-8")).hexdigest() + "\n"
    if SHA_PATH.read_text(encoding="utf-8") != expected_sha:
        raise SystemExit("OpenAPI SHA is stale.")


if __name__ == "__main__":
    main()
