from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SERVER_ROOT = REPO_ROOT / "server"
if str(SERVER_ROOT) not in sys.path:
    sys.path.insert(0, str(SERVER_ROOT))

from app.main import app  # noqa: E402


OUT_DIR = REPO_ROOT / "shared" / "contracts" / "openapi"
OPENAPI_PATH = OUT_DIR / "happyword-api.openapi.json"
PATHS_PATH = OUT_DIR / "happyword-api.paths.txt"
SHA_PATH = OUT_DIR / "happyword-api.sha256"


def normalized_openapi() -> dict[str, object]:
    data = app.openapi()
    data["info"]["x-contract-source"] = "server/app/main.py"
    data["info"]["x-contract-note"] = (
        "Generated by tools/contracts/export_openapi.py. Do not edit by hand."
    )
    return data


def write_contracts() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = normalized_openapi()
    payload = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    OPENAPI_PATH.write_text(payload, encoding="utf-8")
    PATHS_PATH.write_text(
        "\n".join(sorted(data["paths"].keys())) + "\n",
        encoding="utf-8",
    )
    SHA_PATH.write_text(
        hashlib.sha256(payload.encode("utf-8")).hexdigest() + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    write_contracts()
