#!/usr/bin/env bash
# ArkTS:WARN gate for the HarmonyOS build (CLAUDE.md / .cursor/ohos-dev-commands.md §1).
#
# Usage:
#   scripts/check_arkts_warnings.sh <hvigor-build-log>
#   cd harmonyos && hvigorw assembleHap --no-daemon 2>&1 | ../scripts/check_arkts_warnings.sh
#
# Exits 0 when the log contains no disallowed ArkTS:WARN; exits 1 and prints
# the offending file/message pairs otherwise.
#
# The ONLY allowed warnings are these two messages, and only for files under
# ets/cocosvendor/ (the Cocos engine adapter regenerated by
# tools/cocos/build-harmonyos.sh — see cocos/README.md "Known quirks
# (HarmonyOS side)"):
#   * '"globalThis" is not supported (arkts-no-globalthis)'
#       The native engine looks these functions up on the worker's global
#       object via napi; ArkTS has no compliant way to define real globals,
#       so the vendored adapter cannot avoid globalThis.
#   * 'Function may throw exceptions. Special handling is required.'
#       Advisory hint on worker.MessagePort.postMessage inside the vendored
#       message pump; wrapping it in try/catch would change engine plumbing
#       we deliberately keep pristine.
# Everything else — deprecated APIs, missing-permission hints, any warning in
# our own code — must be fixed at the source, never filtered here.
#
# NOTE: ArkTS warnings only surface when a file is actually recompiled, so
# this gate is meaningful on a cold(ish) build. When touching cocosvendor/ or
# the warning gate itself, force recompilation first, e.g.:
#   find harmonyos/entry/src/main/ets -name '*.ets' -o -name '*.ts' | xargs touch
set -euo pipefail

LOG="${1:-/dev/stdin}"

# Strip ANSI color codes, pair each "ArkTS:WARN File:" line with the message
# line that follows it, then report anything outside the allowlist above.
sed -e $'s/\x1b\\[[0-9;]*m//g' "$LOG" | awk '
    /ArkTS:WARN File:/ { file = $0; expect = 1; next }
    expect == 1 {
        expect = 0
        if (file ~ /\/ets\/cocosvendor\// &&
            ($0 ~ /arkts-no-globalthis/ ||
             $0 ~ /Function may throw exceptions/)) { allowed++; next }
        print file
        print $0
        bad++
        next
    }
    END {
        printf("arkts-warn gate: %d disallowed, %d allowed (vendored cocos adapter)\n",
               bad, allowed)
        if (bad > 0) exit 1
    }
'
